// This file is generated

I_birth_place_0 = [
"",
"",
"",
"",
"",
"",
"",
"New York, United States",
"",
"France",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"Saint Petersburg, Pinellas, Florida, United States",
"",
"",
"",
"",
"Elmira, Chemung, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Shinglehouse, Potter, Pennsylvania, United States",
"",
"New York, United States",
"Hollidaysburg, Blair, Pennsylvania, United States",
"",
"New York, United States",
"",
"",
"Germany",
"New York, United States",
"France",
"France",
"",
"Buffalo, Erie, New York, United States",
"Buffalo, Erie, New York, United States",
"New York, United States",
"Orangeville, Wyoming, New York, United States",
"New York, United States",
"",
"",
"New York, United States",
"New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Germany",
"",
"",
"",
"",
"",
"Sharon Center, Potter, Pennsylvania, United States",
"Potter, Pennsylvania, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Smethport, McKean, Pennsylvania, United States",
"Frankford, Hastings, Ontario, Canada",
"Wiscoy, Allegany, New York, United States",
"Rome, Oneida, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"Wethersfield, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"Gainesville, Wyoming, New York, United States",
"",
"Gainesville, Wyoming, New York, United States",
"Gainesville, Wyoming, New York, United States",
"Tyringham, Berkshire, Massachusetts, United States",
"",
"",
"",
"",
"",
"",
"Stillwater, Sussex, New Jersey, United States",
"",
"",
"",
"",
"",
"",
"Lewistown, Mifflin, Pennsylvania, United States",
"Olean, Cattaraugus, New York, United States",
"",
"Centerville, Allegany, New York, United States",
"New York, United States",
"",
"Altoona, Blair, Pennsylvania, United States",
"Bedford, Bedford County, Pennsylvania, United States",
"Warren, Warren, Pennsylvania, United States",
"Altoona, Blair, Pennsylvania, United States",
"",
"",
"McVeytown, Mifflin, Pennsylvania, United States",
"Pennsylvania, United States",
"Allegany, Cattaraugus, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Wethersfield, Wyoming, New York, United States",
"",
"",
"Varysburg, Wyoming, New York, United States",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"Carlsbad, Eddy, New Mexico, United States",
"",
"",
"Chillicothe, Hardeman, Texas, United States",
"Warsaw, Wyoming, New York, United States",
"Ponoka, Alberta, Canada",
"Warsaw, Wyoming, New York, United States",
"Brockport, Monroe, New York, United States",
"Rochester, Monroe, New York, United States",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"Pennsylvania, United States",
"Harrisburg, Dauphin, Pennsylvania, United States",
"Pennsylvania, United States",
"Pennsylvania, United States",
"",
"Roulette, Potter, Pennsylvania, United States",
"Chenango, New York, United States",
"Liberty, McKean, Pennsylvania, United States",
"",
"Roulette, Potter, Pennsylvania, United States",
"Roulette, Potter, Pennsylvania, United States",
"Roulette, Potter, Pennsylvania, United States",
"Pennsylvania, United States",
"Port Allegany, McKean, Pennsylvania, United States",
"",
"Roulette, Potter, Pennsylvania, United States",
"",
"",
"Smethport, McKean, Pennsylvania, United States",
"Burtville, McKean, Pennsylvania, United States",
"Olean, Cattaraugus, New York, United States",
"Roulette, Potter, Pennsylvania, United States",
"Pennsylvania, United States",
"Hazel Hurst, McKean, Pennsylvania, United States",
"McKean, Pennsylvania, United States",
"Olean, Cattaraugus, New York, United States",
"Pennsylvania, United States",
"",
"",
"",
"",
"",
"United States",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"Darien, Livingston, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"Silver Springs, Wyoming, New York, United States",
"Castile, Wyoming, New York, United States",
"West Sparta, Livingston, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Irwin, Gunnison, Colorado, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"Canaseraga, Allegany, New York, United States",
"",
"Attica, Wyoming, New York, United States",
"",
"New York, United States",
"",
"Castile, Wyoming, New York, United States",
"",
"Wyoming, New York, United States",
"",
"Attica, Wyoming, New York, United States",
"Castile, Wyoming, New York, United States",
"",
"Attica, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"Rock Glen, Wyoming, New York, United States",
"",
"Chicago, Cook County, Illinois, United States",
"Springfield, Sangamon, Illinois, United States",
"Chicago, Cook County, Illinois, United States",
"Chicago, Cook County, Illinois, United States",
"",
"",
"Penfield, Monroe, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Horseheads, Chemung, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Germany",
"",
"India",
"",
"Warsaw, Wyoming, New York, United States",
"",
"India",
"",
"",
"Brockport, Monroe, New York, United States",
"Brockport, Monroe, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Kendall, Orleans, New York, United States",
"Brockport, Monroe, New York, United States",
"Brockport, Monroe, New York, United States",
"",
"Alamosa, Alamosa, Colorado, United States",
"Carlsbad, Eddy, New Mexico, United States",
"Carlsbad, Eddy, New Mexico, United States",
"",
"",
"Olean, Cattaraugus, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Hempstead, Nassau, New York, United States",
"Kent, England",
"",
"",
"Shinglehouse, Potter, Pennsylvania, United States",
"Sharon, Potter, Pennsylvania, United States",
"Bells Run, McKean, Pennsylvania, United States",
"Shinglehouse, Potter, Pennsylvania, United States",
"Binghamton, Broome, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Minneapolis, Hennepin, Minnesota, United States",
"",
"Minneapolis, Hennepin, Minnesota, United States",
"",
"",
"",
"",
"",
"Allegany, Cattaraugus, New York, United States",
"",
"Olean, Cattaraugus, New York, United States",
"Olean, Cattaraugus, New York, United States",
"Olean, Cattaraugus, New York, United States",
"",
"Washington, D.C., United States",
"",
"",
"",
"",
"Pennsylvania, United States",
"Pennsylvania, United States",
"Pennsylvania, United States",
"Germany",
"Pennsylvania, United States",
"Pennsylvania, United States",
"",
"",
"",
"Attica, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"Attica, Wyoming, New York, United States",
"Wethersfield, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"Wethersfield, Wyoming, New York, United States",
"Orangeville, Wyoming, New York, United States",
"Attica, Wyoming, New York, United States",
"Greenbush, Rensselaer County, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Wethersfield, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Syracuse, Onondaga, New York, United States",
"",
"",
"",
"",
"",
"",
"Wethersfield, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Alsace, Germany",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"Wethersfield, Wyoming, New York, United States",
"",
"Attica, Wyoming, New York, United States",
"",
"Wethersfield, Wyoming, New York, United States",
"Poplar Tree Corners, Wethersfield, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"Vietnam",
"",
"Vietnam",
"",
"",
"",
"",
"Alsace, Germany",
"",
"Albany, Albany, New York, United States",
"Bavaria, Germany",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"Vietnam",
"",
"",
"Germany",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Wyoming, Wyoming, New York, United States",
"Wethersfield, Wyoming, New York, United States",
"",
"Wethersfield, Wyoming, New York, United States",
"",
"Orangeville, Wyoming, New York, United States",
"",
"Attica, Wyoming, New York, United States",
"",
"",
"",
"Attica, Wyoming, New York, United States",
"",
"",
"",
"Attica, Wyoming, New York, United States",
"",
"Middlebury, Wyoming, New York, United States",
"",
"Wethersfield, Wyoming, New York, United States",
"Orangeville, Wyoming, New York, United States",
"Attica, Wyoming, New York, United States",
"",
"",
"Bavaria, Germany",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"Attica, Wyoming, New York, United States",
"",
"",
"",
"Wyoming, Wyoming, New York, United States",
"Olean, Cattaraugus, New York, United States",
"Binghamton, Broome, New York, United States",
"Wyoming, Wyoming, New York, United States",
"Binghamton, Broome, New York, United States",
"Binghamton, Broome, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Germany",
"Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Attica, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Fort Worth, Tarrant, Texas, United States",
"Fort Worth, Tarrant, Texas, United States",
"",
"",
"",
"",
"",
"",
"Wethersfield, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"Ann Arbor, Washtenaw, Michigan, United States",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"Orangeville, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"Indianapolis, Marion, Indiana, United States",
"",
"",
"",
"",
"Portsmouth, Virginia, United States",
"United States Naval Training Center Bainbridge, Port Deposit, Cecil, Maryland, United States",
"Rice Lake, Barron, Wisconsin, United States",
"Warsaw, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Batavia, Genesee, New York, United States",
"Torrej\u00f3n Air Base, Madrid, Spain",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"Oskaloosa, Mahaska County, Iowa, United States",
"Denver, Denver, Colorado, United States",
"Carlsbad, Eddy, New Mexico, United States",
"",
"Denver, Denver, Colorado, United States",
"Denver, Denver, Colorado, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Wyoming, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"Hassen, Germany",
"Orangeville, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Rochester, Monroe, New York, United States",
"",
"New York, United States",
"",
"Warsaw, Wyoming, New York, United States",
"New York, United States",
"New York, United States",
"",
"Baden-W\u00fcrttemberg, Germany",
"Baden-W\u00fcrttemberg, Germany",
"Warsaw, Wyoming, New York, United States",
"",
"New York, United States",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"New York, United States",
"Warsaw, Wyoming, New York, United States",
"Orangeville, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"Rock Glen, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"Portageville, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"Buffalo, Erie, New York, United States",
"",
"Buffalo, Erie, New York, United States",
"",
"",
"Charlton, Worcester, Massachusetts, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Oxford, Worcester, Massachusetts, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Brockport, Monroe, New York, United States",
"Brockport, Monroe, New York, United States",
"Brockport, Monroe, New York, United States",
"Brockport, Monroe, New York, United States",
"Kendall, Orleans, New York, United States",
"Bedford, Bedford County, Pennsylvania, United States",
"Bedford, Bedford County, Pennsylvania, United States",
"",
"",
"",
"",
"Appleton, Outagamie, Wisconsin, United States",
"",
"",
"",
"",
"",
"Covington, Wyoming, New York, United States",
"Covington, Wyoming, New York, United States",
"Pennsylvania, United States",
"Warsaw, Wyoming, New York, United States",
"Pennsylvania, United States",
"Warsaw, Wyoming, New York, United States",
"Covington, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Pennsylvania, United States",
"Wyoming, Wyoming, New York, United States",
"United States",
"Elk, Pennsylvania, United States",
"Covington, Wyoming, New York, United States",
"Hastings, Ontario, Canada",
"Canada",
"Hastings, Ontario, Canada",
"Trois-Rivi\u00e8res, Quebec, Canada",
"Covington, Wyoming, New York, United States",
"Covington, Wyoming, New York, United States",
"Hastings, Ontario, Canada",
"Pennsylvania, United States",
"Canada",
"Penfield, Clearfield, Pennsylvania, United States",
"Penfield, Clearfield, Pennsylvania, United States",
"Hastings, Ontario, Canada",
"Warsaw, Wyoming, New York, United States",
"Canada",
"Pennsylvania, United States",
"Cross Fork, Potter, Pennsylvania, United States",
"",
"Unityville, Lycoming, Pennsylvania, United States",
"Pennsylvania, United States",
"Unityville, Lycoming, Pennsylvania, United States",
"Pennsylvania, United States",
"Cross Fork, Potter, Pennsylvania, United States",
"",
"Pennsylvania, United States",
"",
"",
"Florida, United States",
"",
"",
"",
"Attica, Wyoming, New York, United States",
"Attica, Wyoming, New York, United States",
"",
"",
"Germany",
"",
"",
"",
"New York, United States",
"New York City, New York, New York, United States",
"New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"Brooklyn, Kings, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Lancaster, Lancaster, Pennsylvania, United States",
"Saint Petersburg, Pinellas, Florida, United States",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"Wethersfield, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"Attica, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Altoona, Blair, Pennsylvania, United States",
"",
"Altoona, Blair, Pennsylvania, United States",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Edelhausen, Dillenburg, Nasaur, Germany",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"Orangeville, Wyoming, New York, United States",
"Orangeville, Wyoming, New York, United States",
"Orangeville, Wyoming, New York, United States",
"",
"",
"Attica, Wyoming, New York, United States",
"",
"Castile, Wyoming, New York, United States",
"",
"Perry, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"Buffalo, Erie, New York, United States",
"Castile, Wyoming, New York, United States",
"Orangeville, Wyoming, New York, United States",
"",
"Buffalo, Erie, New York, United States",
"",
"",
"Chicago, Cook County, Illinois, United States",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"Attica, Wyoming, New York, United States",
"",
"Buffalo, Erie, New York, United States",
"Bliss, Wyoming, New York, United States",
"Perry, Wyoming, New York, United States",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"Oberkutzehhausen, Alsace-Lorraine, France",
"",
"",
"Batavia, Genesee, New York, United States",
"Orangeville, Wyoming, New York, United States",
"",
"Castile, Wyoming, New York, United States",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"Carlsbad, Eddy, New Mexico, United States",
"",
"Buffalo, Erie, New York, United States",
"Buffalo, Erie, New York, United States",
"",
"",
"Attica, Wyoming, New York, United States",
"Orangeville, Wyoming, New York, United States",
"",
"",
"France",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Hector, Potter, Pennsylvania, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Middlebury, Wyoming, New York, United States",
"Rock Glen, Wyoming, New York, United States",
"",
"",
"Warsaw, Wyoming, New York, United States",
"Rochester, Monroe, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Oneonta, Otsego, New York, United States",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"Longview, Gregg, Texas, United States",
"Longview, Gregg, Texas, United States",
"",
"Hereford, Deaf Smith, Texas, United States",
"Carlsbad, Eddy, New Mexico, United States",
"Carlsbad, Eddy, New Mexico, United States",
"Carlsbad, Eddy, New Mexico, United States",
"Carlsbad, Eddy, New Mexico, United States",
"",
"United States",
"",
"New York, United States",
"",
"",
"New York, United States",
"West Seneca, Erie, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"Attica, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"Perry, Wyoming, New York, United States",
"",
"",
"",
"",
"Niagara Falls, Niagara, New York, United States",
"Midland, Midland County, Michigan, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"Homer, Cortland, New York, United States",
"",
"",
"",
"",
"Maryland, United States",
"Washington, D.C., United States",
"",
"United States",
"New York, United States",
"Orangeville, Wyoming, New York, United States",
"New York, United States",
"Orangeville, Wyoming, New York, United States",
"New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Batavia, Genesee, New York, United States",
"",
"Berwick, Columbia, Pennsylvania, United States",
"Wyoming, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Batavia, Genesee, New York, United States",
"Batavia, Genesee, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"Medina, Orleans, New York, United States",
"Warsaw, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"Rochester, Monroe, New York, United States",
"Germany",
"Waltham, Middlesex, Massachusetts, United States",
"Cape Breton, Nova Scotia, Canada",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Attica, Wyoming, New York, United States",
"Attica, Wyoming, New York, United States",
"Washington, D.C., United States",
"",
"Washington, D.C., United States",
"Attica, Wyoming, New York, United States",
"",
"",
"McKean, Pennsylvania, United States",
"",
"Warsaw, Wyoming, New York, United States",
"Rochester, Monroe, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"New York, United States",
"",
"",
"",
"",
"Bavaria, Germany",
"Durnstein, Rheinplaz, Biern, Germany",
"",
"Brumath, Alsace, Germany",
"",
"",
"",
"",
"",
"",
"",
"Buffalo, Erie, New York, United States",
"Geneseo, Livingston, New York, United States",
"",
"United States",
"United States",
"Germany",
"New York, United States",
"United States",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Stevensville, Fort Erie, Niagara, Ontario, Canada",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"New York, United States",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"Sheldon, Wyoming, New York, United States",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"Wyoming, New York, United States",
"",
"",
"",
"",
"Brumath, Alsace, Germany",
"",
"",
"New York, United States",
"",
"",
"Orangeville, Wyoming, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Akron, Erie, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Baden-W\u00fcrttemberg, Germany",
"",
"",
"",
"Orangeville, Wyoming, New York, United States",
"",
"",
"Batavia, Genesee, New York, United States",
"",
"Pine Summit, Columbia, Pennsylvania, United States",
"Perry, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Darien, Livingston, New York, United States",
"",
"",
"",
"",
"",
"Fillmore, Allegany, New York, United States",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"Batavia, Genesee, New York, United States",
"Batavia, Genesee, New York, United States",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"Wethersfield, Wyoming, New York, United States",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"New York, United States",
"",
"",
"",
"East Aurora, Erie, New York, United States",
"Buffalo, Erie, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"Orangeville, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"United States",
"Middlebury, Wyoming, New York, United States",
"Farmersville, Cattaraugus, New York, United States",
"Davin, Logan, West Virginia, United States",
"",
"",
"Olean, Cattaraugus, New York, United States",
"Brockport, Monroe, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"Warsaw, Wyoming, New York, United States",
"",
"Warsaw, Wyoming, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"Wellington, Collingsworth, Texas, United States",
"Roanoke, Virginia, United States",
"Fort Worth, Tarrant, Texas, United States",
"Dodge City, Ford County, Kansas, United States",
"",
"",
"",
"",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
