// This file is generated

S_title_0 = [
"1850 United States Federal Census",
"1860 United States Federal Census",
"1870 United States Federal Census",
"1875 New York Census",
"1880 United States Federal Census",
"1881 Canadian Census",
"1900 United States Federal Census",
"1910 United States Federal Census",
"1915 New York Census",
"1920 United States Federal Census",
"1925 New York Census",
"1930 United States Federal Census",
"1940 United States Federal Census",
"Ancestry",
"Bedford Gazette",
"Biographical review",
"Buffalo News",
"Conner Family Funeral Home",
"Crawford Reunion Info",
"Death Certificates, Pennsylvania Department of Health",
"Delaware, U.S., Marriage Records, 1750-1954",
"Descendants of Nicholas Fisher",
"Facebook",
"Find A Grave",
"Fisher Family Ancestry",
"History of Wyoming County, N.Y.",
"Interview with Josh Herman",
"Interview with Ruth Carlson",
"Legacy.com",
"Marriage Certificates, New York State",
"Massachusetts, Town Clerk, Vital and Town Records, 1626-2001",
"McKean County Democrat",
"New York State, Birth Index, 1881-1942",
"New York State, Marriage Index",
"New York State, Marriage Index, 1881-1967",
"New York State, U.S., Death Index, 1957-1969",
"New York, New York City Marriage Records, 1829-1940",
"New York, U.S., County Marriage Records, 1847-1849, 1907-1936",
"New York, U.S., New York National Guard Service Cards, 1917-1954",
"Olean Evening Times",
"Olean Times Herald",
"Ontario, Canada, Marriages, 1826-1938",
"Penfield Weekly Press",
"Pennsylvania, County Marriages, 1885-1950",
"Pennsylvania, U.S., Birth Certificates, 1906-1913",
"Pennsylvania, U.S., Marriages, 1852-1968",
"Pennsylvania, U.S., Veteran Compensation Application Files, WWII, 1950-1966",
"Rochester Democrat and Chronicle",
"State of New York, Department of Health",
"The Bradford (Pa.) Era",
"The Potter Enterprise",
"Tribute Archive",
"U.S., Headstone Applications for Military Veterans, 1925-1970",
"U.S., National Cemetery Interment Control Forms, 1928-1962",
"U.S., Social Security Applications and Claims Index, 1936-2007",
"U.S., Social Security Death Index, 1935-2014",
"Unknown Newspaper",
"Warsaw Pennysaver",
"Washington Deaths and Burials, 1810-1960",
"Week Funeral Home",
"World War I Draft Cards",
"World War II Draft Cards",
"Wyoming County Times",
"Wyoming, New York, U.S., County Marriage Records"
]
Dwr.ScriptLoaded('dwr_db_S_title_0.js');
